### ISSUE TITLE
nuPlan dataset

### ISSUE THREAD

**Issue by MTDzi** [nvr-avg/trajdata#15]
Are you planning to add support for the nuPlan dataset?

**Comment by BorisIvanovic** [comment]
Thanks for your question!

Yes I am. I would say nuPlan and the Waymo Open Motion Dataset are the core next ones to add.

I don't have any good estimates timeline-wise, but this would likely happen in the fall or early next year (hard to predict at this point).

**Comment by MTDzi** [comment]
Thanks for the response!
