### ISSUE TITLE
Scene centric mode

### ISSUE THREAD

**Issue by Leon0402** [nvr-avg/trajdata#2]
Hi, 

I noticed that UnifiedDataset is not working with the `centric="scene"` option ,because some methods are missing such as `load_all_agent_data`. Is this intentional and functionality will be added at a later point?

**Comment by BorisIvanovic** [comment]
Hi @Leon0402 , thanks for reaching out!

Yes, we have actually just implemented this feature internally, and will soon roll it out to this public version of the codebase, sorry that I did not include it in the initial release!
