### ISSUE TITLE
SimulationScence `get_obs` throws eror if no agents exists

### ISSUE THREAD

**Issue by Leon0402** [nvr-avg/trajdata#4]
When calling `get_obs` with a current scene timestamp without any agent, the code throws an error. 

If `self.agents` is empty, then `agent_data_list` will be empty to:
https://github.com/nvr-avg/trajdata/blob/7c8f7f597997bd3d5ee56b207d2122cc14f1e858/src/trajdata/simulation/sim_scene.py#L109-L110
and passed empty to: 
https://github.com/nvr-avg/trajdata/blob/7c8f7f597997bd3d5ee56b207d2122cc14f1e858/src/trajdata/simulation/sim_scene.py#L135-L139

Then `agent_collate_fn` throws a couple of errors. The first one will be here: 
https://github.com/nvr-avg/trajdata/blob/7c8f7f597997bd3d5ee56b207d2122cc14f1e858/src/trajdata/data_structures/collation.py#L112

Can be reproduced with the `biwi_eth` datasets and an `init_timestep` for the SimulationScene around 200. There are a couple of timesteps with no present agent. 

Fixes might be returning None or construct an empty AgentBatch. This has some impact on the examples, because `new_xyh_dict` will be an empty dict and thus `step` throws errors. I fixed these by adding a check in
https://github.com/nvr-avg/trajdata/blob/7c8f7f597997bd3d5ee56b207d2122cc14f1e858/src/trajdata/simulation/sim_df_cache.py#L122-L128
and only modify the dataframe if `sim_dict` contains elements.

**Comment by BorisIvanovic** [comment]
Good catch @Leon0402! I've opted to raise a ValueError for this and ask the user to choose a different initial timestep. There's not really much one can do with zero agents for simulation 🤷‍♂️
